# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin

name: SlimefunZT
version: ${project.version}
author: zimzaza4
main: cn.zimzaza4.slimefunzt.SlimefunZT
depend: [Slimefun]
loadbefore:
- SlimeCustomizer
- Multiverse-Core
api-version: 1.17
