# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin

name: SlimefunZT
version: 2.0
author: zimzaza4
main: cn.zimzaza4.slimefunzt.SlimefunZT
depend: [Slimefun, WorldEdit, InfinityExpansion]
loadbefore:
- SlimeCustomizer
softdepend:
  - EliteMobs
  - GeneticChickengineering
api-version: 1.21
